### ISSUE TITLE
PoE / PoE+ Specs possibly out of scope...

### ISSUE THREAD

**Issue by hdell** [Uptime-Lab/ComputeBlade#2]
- PoE+ and use 25.5W as the MAX as per IEEE 802.3at-2009 spec; 30W is surge power for a very short period of time. 
- Also, regular PoE is 12.95W MAX as per IEEE 802.3af-2003 spec; 15W is surge power for a very short period of time.

Her are the two open references that I found that describe POE:
1. https://en.wikipedia.org/wiki/Power_over_Ethernet
2. https://www.inscapedata.com/pdf/IEEE802.3at_Standard.pdf

Thus far I found two place that need updating for POE:
1. docs.computeblade.com/about/ and 
2. docs.computeblade.com/main-features/ethernet/.
(Plus please remove the extra backslash; also can you include a reference the PN # of the PoE module so one can look up the specs. Using AG5400 Series?)

Finally, I would add some comments that PoE Network Switches not always provide full MAX W (25.5W x N Ports). For example, a 16 Port Netgear only can provide 76W for PoE+ without adding an additional PSU plus Netgear has different models with different MAX W. There has been some discussion on in the Discord on this topic. For example:

https://www.amazon.com/NETGEAR-16-Port-Gigabit-Ethernet-Unmanaged/dp/B01HUOE12G @ 76W vs
https://www.amazon.com/NETGEAR-16-Port-Gigabit-Ethernet-Unmanaged/dp/B07DNT7JCT @ 183W vs
https://www.amazon.com/NETGEAR-16-Port-Gigabit-Ethernet-Unmanaged/dp/B08CQ8HVD3 @ 260W

Also, folks wanted to know how much the cost of power would be running blades 24/7. I calculated a 100W budget for 10 Blades; cost should not be more than $1 USD per Day (rounded up for cost variance) using average kWh energy usage fee in USA to get a base line understanding. That is equal to skipping 3 Cups of Coffee at Starbucks (average cost per Cup of $3.15 USD) to save enough monies to cover the power usage for the week. Some Folks are on a tight budget, and I wanted to relate this to something a person could easily understand and choose to skip to pay for the cost of power for the Blades.

**Comment by hdell** [comment]
I just found some of the details everyone has been asking about on Discord; in the FAQ under "How much does it cost in electricity?" and "Power Consumption and the choice of the switch".

**Comment by pxpunx** [comment]
I pushed the linked PR, then saw this issue. Most of what you've raised here was covered by my original commit, but I added a few additional corrections and some more information based on your suggestions.

**Comment by hdell** [comment]
I am sorry I don't understand any of this... Are you saying you have made changes or going to make changes? I am noob with all these things like "liked PR", Discord, Git and such. 

The docs give the impression that one can continuously draw "up to 30W" which IMHO is incorrect based upon all of the IEEE specs and other research materials that that I provided here and on Discord https://discordapp.com/channels/952334175501946902/1082921571183771658. Can you 1) please describe how to find your comments that you mention or can import or provide a URL to this content here for completeness; and 2) what is the MAX W that we are agreeing upon? What is the PoE SIL that the Blade uses so we can be more specific?
